[test]
levels = ["syntax", "coverage", "install", "javascript", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
timeout = 600
cpu = []
cuda = !["Unique3D_3_Mesh_Reconstruction","FlexiCubes_Multi-View_Depth_plus_Optional_Normal_maps_to_3D_Mesh", "MV-Adapter-tg2mv"]

# hunyuan3d_v2, 
[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable", "macos_desktop", "windows_desktop", "linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]